#############################################################################
# Makefile for building: InverseKinematic
# Generated by qmake (2.01a) (Qt 4.8.7) on: Tue Jul 4 22:19:09 2017
# Project:  InverseKinematic/InverseKinematic.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile InverseKinematic/InverseKinematic.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -IInverseKinematic -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -IInverseKinematic -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = InverseKinematic/main.cpp \
		InverseKinematic/mainwindow.cpp \
		InverseKinematic/kinematicswidget.cpp \
		InverseKinematic/kinematicsmodel.cpp moc_mainwindow.cpp \
		qrc_shaders.cpp
OBJECTS       = main.o \
		mainwindow.o \
		kinematicswidget.o \
		kinematicsmodel.o \
		moc_mainwindow.o \
		qrc_shaders.o
DIST          = InverseKinematic/fshader.frag \
		InverseKinematic/vshader.vert \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		InverseKinematic/InverseKinematic.pro
QMAKE_TARGET  = InverseKinematic
DESTDIR       = 
TARGET        = InverseKinematic

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: InverseKinematic/InverseKinematic.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile InverseKinematic/InverseKinematic.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile InverseKinematic/InverseKinematic.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/InverseKinematic1.0.0 || $(MKDIR) .tmp/InverseKinematic1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/InverseKinematic1.0.0/ && $(COPY_FILE) --parents InverseKinematic/mainwindow.h InverseKinematic/kinematicswidget.h InverseKinematic/kinematicsmodel.h .tmp/InverseKinematic1.0.0/ && $(COPY_FILE) --parents InverseKinematic/shaders.qrc .tmp/InverseKinematic1.0.0/ && $(COPY_FILE) --parents InverseKinematic/main.cpp InverseKinematic/mainwindow.cpp InverseKinematic/kinematicswidget.cpp InverseKinematic/kinematicsmodel.cpp .tmp/InverseKinematic1.0.0/ && $(COPY_FILE) --parents InverseKinematic/mainwindow.ui .tmp/InverseKinematic1.0.0/ && (cd `dirname .tmp/InverseKinematic1.0.0` && $(TAR) InverseKinematic1.0.0.tar InverseKinematic1.0.0 && $(COMPRESS) InverseKinematic1.0.0.tar) && $(MOVE) `dirname .tmp/InverseKinematic1.0.0`/InverseKinematic1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/InverseKinematic1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: InverseKinematic/mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) InverseKinematic/mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all: qrc_shaders.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_shaders.cpp
qrc_shaders.cpp: InverseKinematic/shaders.qrc
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name shaders InverseKinematic/shaders.qrc -o qrc_shaders.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: InverseKinematic/mainwindow.ui \
		InverseKinematic/kinematicswidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic InverseKinematic/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: InverseKinematic/main.cpp InverseKinematic/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o InverseKinematic/main.cpp

mainwindow.o: InverseKinematic/mainwindow.cpp InverseKinematic/mainwindow.h \
		InverseKinematic/ui_mainwindow.h \
		InverseKinematic/kinematicswidget.h \
		InverseKinematic/kinematicsmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o InverseKinematic/mainwindow.cpp

kinematicswidget.o: InverseKinematic/kinematicswidget.cpp InverseKinematic/kinematicswidget.h \
		InverseKinematic/kinematicsmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kinematicswidget.o InverseKinematic/kinematicswidget.cpp

kinematicsmodel.o: InverseKinematic/kinematicsmodel.cpp InverseKinematic/kinematicsmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kinematicsmodel.o InverseKinematic/kinematicsmodel.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

qrc_shaders.o: qrc_shaders.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_shaders.o qrc_shaders.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

