######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 4 20:12:30 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += kinematicsmodel.h kinematicswidget.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += kinematicsmodel.cpp kinematicswidget.cpp main.cpp mainwindow.cpp
RESOURCES += shaders.qrc
